class Coin < ActiveRecord::Base

  def self.seed_coins
    Coin.sym_list.each do |sym|
      Coin.find_or_create_by(name: sym[:name].upcase, sym: sym[:sym].upcase)
    end
  end

  def self.sym_list
    [
    { name: 'Bitcoin', sym: 'BTC' },
    { name: 'Ripple', sym:  'XRP' },
    { name: 'Ethereum', sym:  'ETH' },
    { name: 'Bitcoin Cash', sym:  'BCH' },
    { name: 'Cardano', sym: 'ADA' },
    { name: 'Litecoin', sym:  'LTC' },
    { name: 'IOTA', sym:  'MIOTA' },
    { name: 'NEM', sym: 'XEM' },
    { name: 'Dash', sym:  'DASH' },
    { name: 'Stellar', sym: 'XLM' },
    { name: 'Monero', sym:  'XMR' },
    { name: 'NEO', sym: 'NEO' },
    { name: 'RaiBlocks', sym: 'XRB' },
    { name: 'Bitcoin Gold', sym:  'BTG' },
    { name: 'Qtum', sym:  'QTUM' },
    { name: 'Ethereum Classic', sym: 'ETC' },
    { name: 'Lisk', sym:  'LSK' },
    { name: 'BitConnect', sym:  'BCC' },
    { name: 'BitShares', sym: 'BTS' },
    { name: 'Verge', sym: 'XVG' },
    { name: 'Zcash', sym: 'ZEC' },
    { name: 'Stratis', sym: 'STRAT' },
    { name: 'Steem', sym: 'STEEM' },
    { name: 'Waves', sym: 'WAVES' },
    { name: 'Hshare', sym:  'HSR' },
    { name: 'Bytecoin', sym:  'BCN' },
    { name: 'Komodo', sym:  'KMD' },
    { name: 'Dogecoin', sym:  'DOGE' },
    { name: 'Siacoin', sym: 'SC' },
    { name: 'Ark', sym: 'ARK' },
    { name: 'Decred', sym:  'DCR' },
    { name: 'DigiByte', sym:  'DGB' },
    { name: 'VeChain', sym: 'VEN' },
    { name: 'Nxt', sym: 'NXT' },
    { name: 'PIVX', sym:  'PIVX' },
    { name: 'Factom', sym:  'FCT' },
    { name: 'MonaCoin', sym:  'MONA' },
    { name: 'ZCoin', sym: 'XZC' },
    { name: 'Syscoin', sym: 'SYS' },
    { name: 'Electroneum', sym: 'ETN' },
    { name: 'BitcoinDark', sym: 'BTCD' },
    { name: 'Vertcoin', sym:  'VTC' },
    { name: 'ReddCoin', sym:  'RDD' },
    { name: 'GameCredits', sym: 'GAME' },
    { name: 'Skycoin', sym: 'SKY' },
    { name: 'Ubiq', sym:  'UBQ' },
    { name: 'BridgeCoin', sym:  'BCO' },
    { name: 'Cryptonex', sym: 'CNX' },
    { name: 'Einsteinium', sym: 'EMC2' },
    { name: 'GXShares', sym:  'GXS' },
    { name: 'SmartCash', sym: 'SMART' },
    { name: 'Blocknet', sym:  'BLOCK' },
    { name: 'BitBay', sym:  'BAY' },
    { name: 'ZClassic', sym:  'ZCL' },
    { name: 'Nexus', sym: 'NXS' },
    { name: 'Particl', sym: 'PART' },
    { name: 'XTRABYTES', sym: 'XBY' },
    { name: 'ZenCash', sym: 'ZEN' },
    { name: 'Rise', sym:  'RISE' },
    { name: 'CloakCoin', sym: 'CLOAK' },
    { name: 'DigitalNote', sym: 'XDN' },
    { name: 'HempCoin', sym:  'THC' },
    { name: 'Emercoin', sym:  'EMC' },
    { name: 'Voxels', sym:  'VOX' },
    { name: 'DECENT', sym:  'DCT' },
    { name: 'Groestlcoin', sym: 'GRS' },
    { name: 'Viacoin', sym: 'VIA' },
    { name: 'Paccoin', sym: 'PAC' },
    { name: 'Achain', sym:  'ACT' },
    { name: 'Spectrecoin', sym: 'XSPEC' },
    { name: 'Peercoin', sym:  'PPC' },
    { name: 'Asch', sym:  'XAS' },
    { name: 'Mooncoin', sym:  'MOON' },
    { name: 'Neblio', sym:  'NEBL' },
    { name: 'Shift', sym: 'SHIFT' },
    { name: 'Burst', sym: 'BURST' },
    { name: 'Gulden', sym:  'NLG' },
    { name: 'Pura', sym:  'PURA' },
    { name: 'PotCoin', sym: 'POT' },
    { name: 'Counterparty', sym:  'XCP' },
    { name: 'SaluS', sym: 'SLS' },
    { name: 'Aeon', sym:  'AEON' },
    { name: 'Feathercoin', sym: 'FTC' },
    { name: 'SIBCoin', sym: 'SIB' },
    { name: 'Elastic', sym: 'XEL' },
    { name: 'SHIELD', sym:  'XSH' },
    { name: 'BlackCoin', sym: 'BLK' },
    { name: 'Namecoin', sym:  'NMC' },
    { name: 'ION', sym: 'ION' },
    { name: 'MinexCoin', sym: 'MNX' },
    { name: 'Lykke', sym: 'LKK' },
    { name: 'FairCoin', sym:  'FAIR' },
    { name: 'WhiteCoin', sym: 'XWC' }
    ]
  end

  def self.sym_list_dep
    [
    'BTC',
    'XRP',
    'ETH',
    'BCH',
    'ADA',
    'LTC',
    'MIOTA',
    'XEM',
    'DASH',
    'XLM',
    'XMR',
    'NEO',
    'XRB',
    'BTG',
    'QTUM',
    'ETC',
    'LSK',
    'BCC',
    'BTS',
    'XVG',
    'ZEC',
    'STRAT',
    'STEEM',
    'WAVES',
    'HSR',
    'BCN',
    'KMD',
    'DOGE',
    'SC',
    'ARK',
    'DCR',
    'DGB',
    'VEN',
    'NXT',
    'PIVX',
    'FCT',
    'MONA',
    'GBYTE',
    'XZC',
    'SYS',
    'ETN',
    'BTCD',
    'KCS',
    'VTC',
    'XP',
    'RDD',
    'GAME',
    'SKY',
    'UBQ',
    'BCO',
    'NAV',
    'CNX',
    'EMC2',
    'GXS',
    'SMART',
    'BLOCK',
    'BAY',
    'ZCL',
    'NXS',
    'PART',
    'XBY',
    'ZEN',
    'RISE',
    'CLOAK',
    'XDN',
    'THC',
    'EMC',
    'VOX',
    'DCT',
    'GRS',
    'VIA',
    'PAC',
    'ACT',
    'XSPEC',
    'PPC',
    'LBC',
    'XAS',
    'MOON',
    'NEBL',
    'ETP',
    'SHIFT',
    'BURST',
    'NLG',
    'PURA',
    'POT',
    'XCP',
    'SLS',
    'AEON',
    'FTC',
    'SIB',
    'XEL',
    'XSH',
    'BLK',
    'NMC',
    'ION',
    'MNX',
    'LKK',
    'FAIR',
    'IOC',
    'XWC']
  end

end
